### ISSUE TITLE
Gradio demo

### ISSUE THREAD

**Issue by xuyu666** [magic-research/InstaDrag#5]
哥，DragDiffusion跟过来的，能搞个demo网址先耍耍么哈哈。

**Comment by Yujun-Shi** [comment]
感谢关注！非常抱歉这个项目现在还在公司审核阶段，所以可能不太方便。有相关demo可以试玩了之后我会在这个issue里面回复哈。谢谢！

**Comment by jongchyisu** [comment]
Hello! Thanks for your good work. Any updates on this?

**Comment by liewjunhao** [comment]
Thank you for your patience. Gradio demo can found [here](https://huggingface.co/spaces/LightningDrag/LightningDrag). Please note that this project is now called [LightningDrag](https://lightning-drag.github.io/) and this repo will be removed soon.
